### ISSUE TITLE
Бахаю ишью про поп-ап 

### ISSUE THREAD

**Issue by artrayme** [fintarin/FintamathAndroid#44]
Привет коллеги, 

На данный момент при удержании пальца на поле с ответом появляется поп-ап с одной функцией "Copy", что в переводе с англосаксонского означает "копирование". Я предлагаю автоматически копировать содержимое ответа в буфер обмена. Кроме того стоит добавить небольшое сообщение снизу, которое сигнализировало бы пользователю о завершении действия копирования (в англосаксонских приложениях обычно выводится "Copied!")

Думайте!

**Comment by artrayme** [comment]
Как там делишки?)))

**Comment by fintarin** [comment]
Доне

**Comment by artrayme** [comment]
ochen' cruto spasibo
